### ISSUE TITLE
center column (60% width) does not extend to the bottom

### ISSUE THREAD

**Issue by close2** [brokenRoX/RCMatura#2]
Stops when text finishes.

![image](https://cloud.githubusercontent.com/assets/364985/21724630/8906a268-d435-11e6-9818-98adfc9dd8f1.png)

(white area should extend to the bottom)

**Comment by enyo** [comment]
SImply use `min-height: 100%;` on the `.center` div.

**Comment by brokenRoX** [comment]
thanks!
